- name: Download Chrome installer
  win_get_url:
    url: https://dl.google.com/chrome/install/GoogleChromeStandaloneEnterprise64.msi
    dest: C:\Windows\Temp\chrome_installer.exe

- name: Install Chrome
  win_package:
    path: C:\Windows\Temp\chrome_installer.exe
    product_id: Google Chrome
    arguments: /silent /install
    creates_path: 'C:\Program Files\Google\Chrome\Application\chrome.exe'

- name: Download Notepad++ installer
  win_get_url:
    url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/latest/download/npp-installer.exe
    dest: C:\Windows\Temp\notepadpp_installer.exe

- name: Install Notepad++
  win_package:
    path: C:\Windows\Temp\notepadpp_installer.exe
    product_id: Notepad++
    arguments: /S
    creates_path: 'C:\Program Files\Notepad++\notepad++.exe'

- name: Download Brave Browser installer
  win_get_url:
    url: https://laptop-updates.brave.com/latest/winx64
    dest: C:\Windows\Temp\brave_installer.exe

- name: Install Brave Browser
  win_package:
    path: C:\Windows\Temp\brave_installer.exe
    product_id: Brave
    arguments: /silent /install
    creates_path: 'C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe'

- name: Install Active Directory RSAT tools
  win_feature:
    name: RSAT-AD-PowerShell
    state: present

- name: Ensure Snipping Tool is enabled
  win_feature:
    name: InkAndHandwritingServices
    state: present

- name: Create Success.txt on the desktop
  win_copy:
    content: "Deployment completed successfully."
    dest: "{{ lookup('env','USERPROFILE') }}\\Desktop\\Success.txt"