- name: Ensure .NET Framework 4.8 is installed
  win_chocolatey:
    name: dotnetfx
    version: 4.8.0.0
    state: present

- name: Install Chocolatey package provider
  win_chocolatey:
    name: chocolatey
    state: present

- name: Install Google Chrome
  win_chocolatey:
    name: googlechrome
    state: present

- name: Install Notepad++
  win_chocolatey:
    name: notepadplusplus
    state: present

- name: Install Brave Browser
  win_chocolatey:
    name: brave
    state: present

- name: Install Active Directory RSAT tools
  win_feature:
    name: RSAT-AD-PowerShell
    state: present

- name: Ensure Snipping Tool is enabled
  win_feature:
    name: InkAndHandwritingServices
    state: present

- name: Create Success.txt on the desktop
  win_copy:
    content: "Deployment completed successfully."
    dest: "{{ lookup('env','USERPROFILE') }}\\Desktop\\Success.txt"