# - name: Install Chocolatey package provider
#   win_chocolatey:
#     name: chocolatey
#     state: present

- name: Download .NET Framework 4.8 installer
  win_get_url:
    url: https://download.visualstudio.microsoft.com/download/pr/1b2ca5df-baad-4194-9edb-83af1a3423f0/d04c77c0326ebc59f4aa440c6455356b/ndp48-web.exe
    dest: C:\Windows\Temp\ndp48-web.exe

- name: Install .NET Framework 4.8
  win_package:
    path: C:\Windows\Temp\ndp48-web.exe
    arguments: /quiet /norestart
    creates_path: 'C:\Program Files\dotnet'

- name: Install Google Chrome
  win_chocolatey:
    name: googlechrome
    state: present

- name: Install Notepad++
  win_chocolatey:
    name: notepadplusplus
    state: present

- name: Install Brave Browser
  win_chocolatey:
    name: brave
    state: present

- name: Install Active Directory RSAT tools
  win_feature:
    name: RSAT-AD-PowerShell
    state: present

- name: Ensure Snipping Tool is enabled
  win_feature:
    name: InkAndHandwritingServices
    state: present

- name: Create Success.txt on the desktop
  win_copy:
    content: "Deployment completed successfully."
    dest: "{{ lookup('env','USERPROFILE') }}\\Desktop\\Success.txt"